#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          weathersnarf
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the weathersnarf service.
### END INIT INFO

SERVICE_NAME="weathersnarf"
NAME="weathersnarf"
USER="weather"

WEATHERSNARF="/home/weather/weathersnarf.rb"
PIDFILE="/tmp/weathersnarf.pid"

. /lib/lsb/init-functions

start_daemon () {
    cd `dirname $WEATHERSNARF` ; (su $USER -c "$WEATHERSNARF" 1>/dev/null 2>&1 &) || log_end_msg $?
    log_end_msg 0
}

kill_daemon () {
    [ -e $PIDFILE ] && kill -9 `cat "$PIDFILE"` && rm -f $PIDFILE
}

case "$1" in
    start)
        log_daemon_msg "Starting weathersnarf"
        start_daemon
        ;;
    stop)
        log_daemon_msg "Stopping weathersnarf"
        kill_daemon
        log_end_msg 0
        ;;
    reload)
        log_daemon_msg "Reloading weathersnarf"
        kill_daemon
        start_daemon
        log_end_msg 0
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting weathersnarf"
        kill_daemon
        start_daemon
        ;;
    status)
        [ -e $PIDFILE ] && kill -0 `cat "$PIDFILE"` >/dev/null 2>&1 && exit 0 || exit $?
        ;;
    *)
        log_action_msg "Usage: /etc/init.d/$NAME {start|stop|reload|force-reload|restart|status}" || true
        exit 2
        ;;
esac

exit 0